kind: Service
apiVersion: v1
metadata:
  name: room-number-ocr
  namespace: ai-ocr
spec:
  selector:
    app: room-number-ocr
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 32088
      port: 32666
      targetPort: 32666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-number-ocr
  labels:
    app: room-number-ocr
  namespace: ai-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-number-ocr
  template:
    metadata:
      labels:
        app: room-number-ocr
    spec:
      containers:
      - name: room-number-ocr
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 32666
